version: 2.1

############
# Defaults #
############
base_defaults: &base_defaults
  environment: &environment
    CIRCLE_TEST_REPORTS: /tmp/test-results
    CIRCLE_ARTIFACTS: /tmp/test-artifacts
    BUNDLE_JOBS: 4
    BUNDLE_RETRY: 3
    BUNDLE_PATH: ~/vendor/bundle
  working_directory: ~/spree_admin

defaults_2_7: &defaults_2_7
  <<: *base_defaults
  docker:
    - image: &ruby_2_7_image cimg/ruby:2.7-browsers

defaults_3_0: &defaults_3_0
  <<: *base_defaults
  docker:
    - image: &ruby_3_0_image cimg/ruby:3.0-browsers


##########################
# Environment Installers #
##########################
# Ruby 2.7
run_tests_2_7: &run_tests_2_7
  <<: *defaults_2_7
  docker:
    - image: &redis_image cimg/redis:7.0
  parallelism: 8
  steps:
    - checkout
    - restore_cache:
        keys:
          - spree-admin-bundle-v05-ruby-2-7-{{ .Branch }}
          - spree-admin-bundle-v05-ruby-2-7
    - run:
        name: Install libvips
        command: sudo apt update && sudo apt-get install libvips
    - run:
        name: Set bundle path
        command: bundle config --local path vendor/bundle
    - run:
        name: Ensure bundle Install
        command: |
          bundle check || bundle install
    - run:
        name: Create Test App
        command: |
          bundle exec rake test_app
    - run:
        name: Run Tests
        command: bundle exec rspec spec
    # - store_test_results:
    #     path: ${CIRCLE_TEST_REPORTS}
    # - store_artifacts:
    #     path: ${CIRCLE_ARTIFACTS}

# Ruby 3.0
run_tests_3_0: &run_tests_3_0
  <<: *defaults_3_0
  docker:
    - image: *redis_image
  parallelism: 8
  steps:
    - checkout
    - restore_cache:
        keys:
          - spree-admin-bundle-v05-ruby-3-0-{{ .Branch }}
          - spree-admin-bundle-v05-ruby-3-0
    - run:
        name: Install libvips
        command: sudo apt update && sudo apt-get install libvips
    - run:
        name: Set bundle path
        command: bundle config --local path vendor/bundle
    - run:
        name: Ensure bundle Install
        command: |
          bundle check || bundle install
    - run:
        name: Create Test App
        command: |
          bundle exec rake test_app
    - run:
        name: Run Rspec
        command: |
          TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
          bundle exec rspec --format documentation \
                            --format RspecJunitFormatter \
                            -o ~/rspec/rspec.xml \
                            -- ${TESTFILES}
    # - store_test_results:
    #     path: ~/rspec
    # - store_artifacts:
    #     path: ${CIRCLE_ARTIFACTS}


########
# Jobs #
########
jobs:
  bundle_ruby_2_7:
    <<: *defaults_2_7
    steps:
      - checkout
      - restore_cache:
          keys:
            - spree-admin-bundle-v05-ruby-2-7-{{ .Branch }}
            - spree-admin-bundle-v05-ruby-2-7
      - run:
          name: Set bundle path
          command: bundle config --local path vendor/bundle
      - run:
          name: Bundle Install
          command: |
            bundle check || bundle install
      - save_cache:
          paths:
            - vendor/bundle
          key: spree-admin-bundle-v05-ruby-2-7-{{ checksum "Gemfile.lock" }}

  bundle_ruby_3_0:
    <<: *defaults_3_0
    steps:
      - checkout
      - restore_cache:
          keys:
            - spree-admin-bundle-v05-ruby-3-0-{{ .Branch }}
            - spree-admin-bundle-v05-ruby-3-0
      - run:
          name: Set bundle path
          command: bundle config --local path vendor/bundle
      - run:
          name: Bundle Install
          command: |
            bundle check || bundle install
      - save_cache:
          paths:
            - vendor/bundle
          key: spree-admin-bundle-v05-ruby-3-0-{{ checksum "Gemfile.lock" }}


  ####################
  # Database Configs #
  ####################
  # PG Ruby 2.7
  tests_postgres_ruby_2_7:
    <<: *run_tests_2_7
    environment: &postgres_environment
      <<: *environment
      DB: postgres
      DB_HOST: localhost
      DB_USERNAME: postgres
    docker:
      - image: *ruby_2_7_image
      - image: *redis_image
      - image: &postgres_image cimg/postgres:14.4
        environment:
          POSTGRES_USER: postgres
  # PG Ruby 3.0
  tests_postgres_ruby_3_0:
    <<: *run_tests_3_0
    environment:
      <<: *postgres_environment
    docker:
      - image: *ruby_3_0_image
      - image: *redis_image
      - image: *postgres_image

  # MYSQL Ruby 2.7
  tests_mysql_ruby_2_7:
    <<: *run_tests_2_7
    environment: &mysql_environment
      <<: *environment
      DB: mysql
      DB_HOST: 127.0.0.1
      DB_USERNAME: root
      COVERAGE: true
      COVERAGE_DIR: /tmp/workspace/simplecov
    docker:
      - image: *ruby_2_7_image
      - image: *redis_image
      - image: &mysql_image cimg/mysql:8.0
  # MYSQL Ruby 3.0
  tests_mysql_ruby_3_0:
    <<: *run_tests_3_0
    environment:
      <<: *mysql_environment
    docker:
      - image: *ruby_2_7_image
      - image: *redis_image
      - image: *mysql_image


#############
# Workflows #
#############
workflows:
  version: 2
  main:
    jobs:
      - bundle_ruby_2_7
      - bundle_ruby_3_0
      - tests_postgres_ruby_3_0:
          requires:
            - bundle_ruby_3_0
      - tests_mysql_ruby_2_7:
          requires:
            - bundle_ruby_2_7
