version: 2.1

############
# Defaults #
############
base_defaults: &base_defaults
  environment: &environment
    CIRCLE_TEST_REPORTS: /tmp/test-results
    CIRCLE_ARTIFACTS: /tmp/test-artifacts
    BUNDLE_JOBS: 4
    BUNDLE_RETRY: 3
    BUNDLE_PATH: ~/spree_admin/vendor/bundle
  working_directory: ~/spree_admin
  docker:
    - image: &redis_image cimg/redis:7.0

defaults_2_7: &defaults_2_7
  <<: *base_defaults
  docker:
    - image: &ruby_2_7_image cimg/ruby:2.7-browsers
    - image: *redis_image

defaults_3_0: &defaults_3_0
  <<: *base_defaults
  docker:
    - image: &ruby_3_0_image cimg/ruby:3.0-browsers
    - image: *redis_image

#############
# Run Tests #
#############
# Ruby 2.7
run_tests_2_7: &run_tests_2_7
  <<: *defaults_2_7
  parallelism: 8
  steps:
    - checkout
    - restore_cache:
        keys:
          - spree-admin-bundle-v10-ruby-2-7-{{ .Branch }}
          - spree-admin-bundle-v10-ruby-2-7
    - run:
        name: Install libvips
        command: sudo apt update && sudo apt-get install libvips
    - run:
        name: Set bundle path
        command: bundle config --local path vendor/bundle
    - run:
        name: Ensure bundle Install
        command: |
          bundle check || bundle install
    - run:
        name: Create Test App
        command: |
          bundle exec rake test_app
    - run:
        name: Run Rspec
        command: |
          TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
          bundle exec rspec --format documentation \
                            --format RspecJunitFormatter \
                            -o ~/rspec/rspec.xml \
                            -- ${TESTFILES}
    - run:
        name: Unlink @spree/admin NPM package
        command: |
          cd spec/dummy && yarn unlink @spree/admin
    - store_test_results:
        path: ~/rspec
    - store_artifacts:
        path: /tmp/test-artifacts

# Ruby 3.0
run_tests_3_0: &run_tests_3_0
  <<: *defaults_3_0
  parallelism: 8
  steps:
    - checkout
    - restore_cache:
        keys:
          - spree-admin-bundle-v10-ruby-3-0-{{ .Branch }}
          - spree-admin-bundle-v10-ruby-3-0
    - run:
        name: Install libvips
        command: sudo apt update && sudo apt-get install libvips
    - run:
        name: Set bundle path
        command: bundle config --local path vendor/bundle
    - run:
        name: Ensure bundle Install
        command: |
          bundle check || bundle install
    - run:
        name: Create Test App
        command: |
          bundle exec rake test_app
    - run:
        name: Run Rspec
        command: |
          TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
          bundle exec rspec --format documentation \
                            --format RspecJunitFormatter \
                            -o ~/rspec/rspec.xml \
                            -- ${TESTFILES}
    - run:
        name: Unlink @spree/admin NPM package
        command: |
          cd spec/dummy && yarn unlink @spree/admin
    - store_test_results:
        path: ~/rspec
    - store_artifacts:
        path: /tmp/test-artifacts

########
# Jobs #
########
jobs:
  bundle_ruby_2_7:
    <<: *defaults_2_7
    steps:
      - checkout
      - restore_cache:
          keys:
            - spree-admin-bundle-v12-ruby-2-7-{{ .Branch }}
            - spree-admin-bundle-v12-ruby-2-7
      - run:
          name: Install libvips
          command: sudo apt update && sudo apt-get install libvips
      - run:
          name: Set bundle path
          command: bundle config --local path vendor/bundle
      - run:
          name: Bundle Install
          command: |
            bundle check || bundle install
      - save_cache:
          paths:
            - vendor/bundle
          key: spree-admin-bundle-v12-ruby-2-7-{{ checksum "Gemfile.lock" }}

  bundle_ruby_3_0:
    <<: *defaults_3_0
    steps:
      - checkout
      - restore_cache:
          keys:
            - spree-admin-bundle-v12-ruby-3-0-{{ .Branch }}
            - spree-admin-bundle-v12-ruby-3-0
      - run:
          name: Install libvips
          command: sudo apt update && sudo apt-get install libvips
      - run:
          name: Set bundle path
          command: bundle config --local path vendor/bundle
      - run:
          name: Bundle Install
          command: |
            bundle check || bundle install
      - save_cache:
          paths:
            - vendor/bundle
          key: spree-admin-bundle-v12-ruby-3-0-{{ checksum "Gemfile.lock" }}

  ####################
  # Database Configs #
  ####################
  # PG Ruby 2.7
  tests_postgres_ruby_2_7:
    <<: *run_tests_2_7
    environment: &postgres_environment
      <<: *environment
      DB: postgres
      DB_HOST: localhost
      DB_USERNAME: postgres
    docker:
      - image: *ruby_2_7_image
      - image: *redis_image
      - image: &postgres_image circleci/postgres:12-alpine
        environment:
          POSTGRES_USER: postgres
  # PG Ruby 3.0
  tests_postgres_ruby_3_0:
    <<: *run_tests_3_0
    environment:
      <<: *postgres_environment
    docker:
      - image: *ruby_3_0_image
      - image: *redis_image
      - image: *postgres_image

  # MYSQL Ruby 2.7
  tests_mysql_ruby_2_7:
    <<: *run_tests_2_7
    environment: &mysql_environment
      <<: *environment
      DB: mysql
      DB_HOST: 127.0.0.1
      DB_USERNAME: root
      COVERAGE: true
      COVERAGE_DIR: /tmp/workspace/simplecov
    docker:
      - image: *ruby_2_7_image
      - image: *redis_image
      - image: &mysql_image circleci/mysql:8-ram
  # MYSQL Ruby 3.0
  tests_mysql_ruby_3_0:
    <<: *run_tests_3_0
    environment:
      <<: *mysql_environment
    docker:
      - image: *ruby_2_7_image
      - image: *redis_image
      - image: *mysql_image

#################
# Run Workflows #
#################
workflows:
  version: 2
  main:
    jobs:
      - bundle_ruby_2_7
      - bundle_ruby_3_0
      - tests_postgres_ruby_3_0:
          requires:
            - bundle_ruby_3_0
      - tests_mysql_ruby_2_7:
          requires:
            - bundle_ruby_2_7
