---
name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
jobs:
  # POSTGRES
  postgres:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.7', '3.0']

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: spree_admin
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
            node-version: 16

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Set up Redis
        uses: shogo82148/actions-setup-redis@v1.19.0

      - name: Install libvips
        run: sudo apt-get install -y libvips

      - name: Build Test App
        env:
          DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/spree_admin
          RAILS_ENV: test
          DB: postgresql
        run: |
          bundle exec rake test_app

      - name: Run Tests
        run: |
          bundle exec rspec spec
